### ISSUE TITLE
Twitch / all channels Overlay : Première version

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/juste-un-curieux-twitch-overlay#1]
@BorisTherin tu suis https://www.youtube.com/watch?v=lKgUwi8hBP8
tu utilises ton propre channel twitch pour fair des tests
tu utilises ton installation de OBS Streamlabs sur ton PC

Et tu suis le tuto d'un gars que j'aime bcp il est bine son taff : https://www.youtube.com/watch?v=lKgUwi8hBP8 

## Contraintes

* tu fonctionne savec git branch, issue, et PR
* la première version que tu fais (première PR), tu fais juste exactement comme le gars fait dans la vidéo, faut juste que ça marche. Le test qu'on fera pour merger ta PR : on lance un live sur ton compte twitch et moi j'iria dans le chat voir si l'overlay est là
* tu as l'obligation d'utiliser uniquement tailwind css
* la deuxième verpon (deuxième PR): je la ferai, je transformerai le projet précédent, pour qu'il siot compilé en typescript avec vitejs, et le résultat dans `./dist/`, sera exactement la même chose que ce que tu as fais en javascript pour la première version
* la troisième version, on va voir ce qu'on peut faire pour aller plus loi
* la quatrième version: là je vais voir  comme faire un plugin de OBS Streamlabs

## Très utile

* Essaies d'utiliser d'abord https://github.com/BenDMyers/showmy.chat  pour faire un overlay pour Justin. 
* Puis tu regarderas si tu peux fork https://github.com/BenDMyers/showmy.chat , afin que Justin Curieux puisses avoir des css spécifiques à Justin Curieux : pour lui générer des overlay très rapidement, avec des design css tailwind que personne d'autre n'a, un peu comme un theme switcher, sauf que là c'est un overlay-switcher, si c'est clair... (on rédigera mieux cette description de use case)

**Comment by BorisTherin** [comment]
aussi :
[https://blog.roboflow.com/use-computer-vision-to-control-obs/](https://blog.roboflow.com/use-computer-vision-to-control-obs/)
![image](https://github.com/3forges/juste-un-curieux-twitch-overlay/assets/89749441/a21609ce-edc7-4865-b0a1-a5ff4060bbc3)

[https://github.com/Tyler-Odenthal/Download-OBS-Controller](https://github.com/Tyler-Odenthal/Download-OBS-Controller)

**Comment by Jean-Baptiste-Lasselle** [comment]
un premier proto est fait mais avec astro et rpeact, sur base de tmi.js : bcp mieux
